import assert from 'node:assert/strict';
import {createInstance} from 'i18next';
import React, {act} from 'react';
import {renderToString} from 'react-dom/server';
import {hydrateRoot} from 'react-dom/client';
import {I18nextProvider} from 'react-i18next';
import {JSDOM} from 'jsdom';
import {messages,literal,registerKtstrings,resolveText,resources,decodeText} from '__PACKAGE__';
import {useKtstrings} from '__PACKAGE__/react';
const i18n=createInstance();
registerKtstrings(i18n);
await i18n.init({lng:'en',fallbackLng:'ar',initImmediate:false,interpolation:{escapeValue:true},keySeparator:'.'});
const heading=messages.welcome({name:'Ada'});
assert.equal(resolveText(i18n,heading),'Welcome, Ada');
assert.equal(resolveText(i18n,heading,'fr-CA'),'Bienvenue, Ada');
assert.equal(resolveText(i18n,heading,' fr '),'Bienvenue, Ada');
assert.equal(resolveText(i18n,messages.itemsCount({count:2}),'ar'),'2 items'); // Arabic message absent: English grammar
assert.equal(resolveText(i18n,literal('')),'');
const generic=literal('Generic');
assert.equal(resolveText(i18n,decodeText({kind:'message',namespace:'acceptance',id:'items.count',arguments:{count:3}},generic)),'3 items');
assert.equal(resolveText(i18n,decodeText({kind:'message',namespace:'acceptance',id:'future',arguments:{},fallbackText:''},generic)),'');
const diagnostics=[];
assert.equal(decodeText({kind:'message',namespace:'acceptance',id:'welcome',arguments:{name:'private',lng:'ar'}},generic,error=>diagnostics.push(error)),generic);
assert.equal(diagnostics[0].code,'INVALID_ARGUMENTS');
assert.ok(!JSON.stringify(diagnostics).includes('private'));
assert.equal(decodeText({kind:'message',namespace:'other',id:'welcome',arguments:{name:'Ada'}},generic),generic);
assert.equal(decodeText({kind:'message',namespace:'acceptance',id:'items.count',arguments:{count:'3'}},generic),generic);
assert.equal(resolveText(i18n,decodeText({kind:'literal',text:''},generic)),'');
const tricky='<b>& {{name}} $t(welcome) __KT0_BEGIN__';
assert.equal(resolveText(i18n,messages.welcome({name:tricky})),'Welcome, '+tricky);
if(messages.literalSyntax) assert.equal(resolveText(i18n,messages.literalSyntax()),'{{value}} $t(welcome) % " \\ $');
for(const count of [-1,0.5,2147483648,NaN,Infinity]) assert.throws(()=>messages.itemsCount({count}));
assert.equal(resolveText(i18n,messages.itemsCount({count:2147483647})),'2147483647 items');
if (messages.signedValue) { assert.equal(resolveText(i18n,messages.signedValue({amount:-2147483648})),'-2147483648'); assert.equal(resolveText(i18n,messages.signedValue({amount:2147483647})),'2147483647'); assert.throws(()=>messages.signedValue({amount:-2147483649})); }
let networkRequests=0;
const previousFetch=globalThis.fetch;
globalThis.fetch=()=>{networkRequests++;throw new Error('Unexpected translation download');};
function Header(){const {text}=useKtstrings();return React.createElement('h1',null,text(heading));}
const tree=React.createElement(I18nextProvider,{i18n},React.createElement(Header));
const html=renderToString(tree);
assert.equal(html,'<h1>Welcome, Ada</h1>');
const dom=new JSDOM('<div id="root">'+html+'</div>',{url:'https://fixture.invalid'});
globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const errors=[];
let root;
await act(async()=>{root=hydrateRoot(document.getElementById('root'),tree,{onRecoverableError:error=>errors.push(error)});});
assert.equal(errors.length,0);
await act(async()=>{await i18n.changeLanguage('fr');});
assert.equal(document.querySelector('h1').textContent,'Bienvenue, Ada');
assert.equal(heading.arguments.name,'Ada');
await act(async()=>{root.unmount();});
assert.equal(networkRequests,0);
globalThis.fetch=previousFetch;
dom.window.close();
const isolated=createInstance();registerKtstrings(isolated);await isolated.init({lng:'en',initImmediate:false});
assert.equal(resolveText(isolated,heading),'Welcome, Ada');
assert.equal(i18n.language,'fr');
assert.ok(resources.en && resources.fr);
