package com.latenighthack.ktstrings.compiler

import java.nio.file.Files
import java.nio.file.Path

class AndroidEmitter : CatalogEmitter {
    override val name = "android"
    override fun emit(catalog: CompiledCatalog, options: GenerationOptions, outputDirectory: Path) {
        val pkg = options.kotlinPackage ?: return
        val androidPackage = options.androidPackage ?: return
        val root = outputDirectory.resolve("android")
        val source = catalog.source
        writeResources(catalog, source.sourceLocale, root.resolve("resources/values"))
        for (locale in catalog.locales) writeResources(catalog, locale, root.resolve("resources/values-b+${locale.replace('-', '+')}"))
        val code = buildString {
            appendLine("// Generated by ktstrings; do not edit.")
            appendLine("package $pkg")
            appendLine("import android.content.Context")
            appendLine("import android.content.res.Configuration")
            appendLine("import android.os.Build")
            appendLine("import java.util.Locale")
            appendLine("import com.latenighthack.ktstrings.*")
            appendLine("import $androidPackage.R")
            appendLine("class AndroidTextResolver(private val context: Context) {")
            appendLine("    @Suppress(\"DEPRECATION\") private fun deviceLocale(): String = if (Build.VERSION.SDK_INT >= 24) context.resources.configuration.locales[0].toLanguageTag() else context.resources.configuration.locale.toLanguageTag()")
            appendLine("    fun resolve(value: UiText, requestedLocale: String = deviceLocale()): String {")
            appendLine("        if (value is LiteralText) return value.text")
            appendLine("        value as LocalMessage")
            appendLine("        require(value.namespace == ${KotlinEmitter.quote(source.namespace)}) { \"Wrong ktstrings catalog namespace\" }")
            appendLine("        val selected = CatalogAvailability.select(value.id, requestedLocale)")
            appendLine("        val configuration = Configuration(context.resources.configuration)")
            appendLine("        configuration.setLocale(Locale.forLanguageTag(selected))")
            appendLine("        val resources = context.createConfigurationContext(configuration).resources")
            appendLine("        return when (value.id) {")
            for (message in source.messages.values) {
                val identifier = Names.resource(source.namespace, message.id)
                val args = message.arguments.joinToString { arg -> "(value.arguments.getValue(${KotlinEmitter.quote(arg.name)}) as ArgumentValue.${if (arg.type == ArgumentType.STRING) "StringValue" else "IntValue"}).value" }
                val call = if (message.body is Body.Plural) {
                    val quantity = "(value.arguments.getValue(${KotlinEmitter.quote(message.body.selector)}) as ArgumentValue.IntValue).value"
                    "resources.getQuantityString(R.plurals.$identifier, $quantity${if (args.isEmpty()) "" else ", $args"})"
                } else "resources.getString(R.string.$identifier${if (args.isEmpty()) "" else ", $args"})"
                appendLine("            ${KotlinEmitter.quote(message.id)} -> $call")
            }
            appendLine("            else -> error(\"Unknown ktstrings message ID\")")
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
        }
        write(root.resolve("kotlin/${pkg.replace('.', '/')}/AndroidTextResolver.kt"), code)
        write(root.resolve("compose/${pkg.replace('.', '/')}/ComposeText.kt"), """
package $pkg
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalConfiguration
import com.latenighthack.ktstrings.UiText
@Composable
fun UiText.resolveText(requestedLocale: String? = null): String {
    val context = LocalContext.current
    val configuration = LocalConfiguration.current
    val resolver = remember(context) { AndroidTextResolver(context) }
    return remember(this, resolver, configuration, requestedLocale) {
        if (requestedLocale == null) resolver.resolve(this) else resolver.resolve(this, requestedLocale)
    }
}
""".trimIndent() + "\n")
    }
    private fun writeResources(catalog: CompiledCatalog, locale: String, directory: Path) {
        val strings = StringBuilder("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<resources>\n")
        val plurals = StringBuilder("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<resources>\n")
        for ((id, body) in catalog.bodies(locale)) {
            val message = catalog.source.messages.getValue(id)
            val name = Names.resource(catalog.source.namespace, id)
            when (body) {
                is Body.Text -> strings.append("  <string name=\"$name\" formatted=\"${message.arguments.isNotEmpty()}\">${format(body.tokens, message)}</string>\n")
                is Body.Plural -> {
                    plurals.append("  <plurals name=\"$name\">\n")
                    for ((category, tokens) in body.cases) plurals.append("    <item quantity=\"$category\">${format(tokens, message)}</item>\n")
                    plurals.append("  </plurals>\n")
                }
            }
        }
        strings.append("</resources>\n"); plurals.append("</resources>\n")
        write(directory.resolve("strings.xml"), strings.toString()); write(directory.resolve("plurals.xml"), plurals.toString())
    }
    private fun format(tokens: List<Token>, message: Message): String {
        val raw = tokens.joinToString("") { token -> when (token) {
            is Token.Literal -> if (message.arguments.isNotEmpty()) token.value.replace("%", "%%") else token.value
            is Token.Placeholder -> {
                val index = message.arguments.indexOfFirst { it.name == token.name }
                "%${index + 1}\$${if (message.arguments[index].type == ArgumentType.STRING) "s" else "d"}"
            }
        } }
        val escaped = buildString {
            for (character in raw) append(when (character) {
                '\\' -> "\\\\"; '\n' -> "\\n"; '\r' -> "\\r"; '\t' -> "\\t"; '"' -> "\\\""; '\'' -> "\\'";
                '&' -> "&amp;"; '<' -> "&lt;"; '>' -> "&gt;"; else -> character.toString()
            })
        }
        return "\"$escaped\""
    }
    private fun write(file: Path, text: String) { Files.createDirectories(file.parent); Files.writeString(file, text) }
}
