package com.latenighthack.ktstrings.compiler

import com.fasterxml.jackson.databind.ObjectMapper
import java.nio.file.Files
import java.nio.file.Path

class KotlinEmitter : CatalogEmitter {
    override val name = "kotlin"
    override fun emit(catalog: CompiledCatalog, options: GenerationOptions, outputDirectory: Path) {
        val pkg = options.kotlinPackage ?: return
        if (!Regex("[A-Za-z][A-Za-z0-9_]*(\\.[A-Za-z][A-Za-z0-9_]*)*").matches(pkg)) throw CatalogException("KOTLIN_PACKAGE", "Invalid Kotlin package '$pkg'")
        val code = buildString {
            appendLine("// Generated by ktstrings; do not edit.")
            appendLine("package $pkg")
            appendLine("import com.latenighthack.ktstrings.*")
            appendLine("sealed class CatalogMessage(id: String) : LocalMessage(${quote(catalog.source.namespace)}, id)")
            for (message in catalog.source.messages.values) {
                val type = "${Names.pascal(message.id)}Message"
                message.description?.let { appendLine("/** ${it.replace("*/", "* /").replace('\n', ' ')} */") }
                if (message.arguments.isEmpty()) appendLine("data object $type : CatalogMessage(${quote(message.id)}) {")
                else appendLine("data class $type(${message.arguments.joinToString { "val ${it.name}: ${type(it.type)}" }}) : CatalogMessage(${quote(message.id)}) {")
                if (message.body is Body.Plural) appendLine("    init { require(${message.body.selector} >= 0) { \"Plural quantity must be non-negative\" } }")
                appendLine("    override val arguments: Map<String, ArgumentValue> get() = ${if (message.arguments.isEmpty()) "emptyMap()" else message.arguments.joinToString(prefix = "mapOf(", postfix = ")") { "${quote(it.name)} to ArgumentValue.${if (it.type == ArgumentType.STRING) "StringValue" else "IntValue"}(${it.name})" }}")
                appendLine("}")
            }
            appendLine("object Messages {")
            for (message in catalog.source.messages.values) {
                val args = message.arguments.joinToString { "${it.name}: ${type(it.type)}" }
                val value = "${Names.pascal(message.id)}Message" + if (message.arguments.isEmpty()) "" else message.arguments.joinToString(prefix = "(", postfix = ")") { it.name }
                appendLine("    fun ${Names.camel(message.id)}($args): ${Names.pascal(message.id)}Message = $value")
            }
            appendLine("    fun decode(value: ServerText, genericFallback: UiText, diagnostics: DiagnosticSink? = null): UiText = CatalogDecoder.decode(value, genericFallback, diagnostics)")
            appendLine("}")
            appendLine("object CatalogDecoder : ServerDecoder(${quote(catalog.source.namespace)}) {")
            appendLine("    override fun decodeKnown(reference: ServerMessage): LocalMessage = when (reference.id) {")
            for (message in catalog.source.messages.values) {
                appendLine("        ${quote(message.id)} -> {")
                appendLine("            DecoderValidation.names(reference, ${message.arguments.joinToString(prefix = "setOf(", postfix = ")") { quote(it.name) }})")
                val args = message.arguments.joinToString { argument ->
                    val plural = message.body is Body.Plural && message.body.selector == argument.name
                    "${argument.name} = DecoderValidation.${if (argument.type == ArgumentType.STRING) "string" else "integer"}(reference, ${quote(argument.name)}${if (plural) ", plural = true" else ""})"
                }
                appendLine("            Messages.${Names.camel(message.id)}($args)")
                appendLine("        }")
            }
            appendLine("        else -> throw DecodeFailure(DecodeError.UNKNOWN_ID)")
            appendLine("    }")
            appendLine("}")
            appendLine("object CatalogAvailability {")
            appendLine("    const val SOURCE_LOCALE: String = ${quote(catalog.source.sourceLocale)}")
            appendLine("    const val CLDR_VERSION: String = ${quote(catalog.cldrVersion)}")
            appendLine("    fun locales(id: String): List<String> = when (id) {")
            for (id in catalog.source.messages.keys) appendLine("        ${quote(id)} -> ${catalog.availableLocales(id).joinToString(prefix = "listOf(", postfix = ")") { quote(it) }}")
            appendLine("        else -> emptyList()")
            appendLine("    }")
            appendLine("    fun select(id: String, requestedLocale: String): String = LocaleSelection.select(requestedLocale, locales(id), SOURCE_LOCALE)")
            appendLine("}")
        }
        val file = outputDirectory.resolve("kotlin/${pkg.replace('.', '/')}/Messages.kt")
        Files.createDirectories(file.parent); Files.writeString(file, code)
    }
    private fun type(type: ArgumentType): String = if (type == ArgumentType.STRING) "String" else "Int"
    companion object {
        fun quote(value: String): String = ObjectMapper().writeValueAsString(value).replace("$", "\\$")
    }
}
